export const DIARY_LIST_REQUEST = "DIARY_LIST_REQUEST";
export const DIARY_LIST_SUCCESS = "DIARY_LIST_SUCCESS";
export const DIARY_LIST_FAIL = "DIARY_LIST_FAIL";

export const DIARY_CREATE_REQUEST = "DIARY_CREATE_REQUEST";
export const DIARY_CREATE_SUCCESS = "DIARY_CREATE_SUCCESS";
export const DIARY_CREATE_FAIL = "DIARY_CREATE_FAIL";

export const DIARY_UPDATE_REQUEST = "DIARY_UPDATE_REQUEST";
export const DIARY_UPDATE_SUCCESS = "DIARY_UPDATE_SUCCESS";
export const DIARY_UPDATE_FAIL = "DIARY_UPDATE_FAIL";

export const DIARY_DELETE_REQUEST = "DIARY_DELETE_REQUEST";
export const DIARY_DELETE_SUCCESS = "DIARY_DELETE_SUCCESS";
export const DIARY_DELETE_FAIL = "DIARY_DELETE_FAIL";
