export const GROCERIES_LIST_REQUEST = "GROCERIES_LIST_REQUEST";
export const GROCERIES_LIST_SUCCESS = "GROCERIES_LIST_SUCCESS";
export const GROCERIES_LIST_FAIL = "GROCERIES_LIST_FAIL";

export const GROCERIES_CREATE_REQUEST = "GROCERIES_CREATE_REQUEST";
export const GROCERIES_CREATE_SUCCESS = "GROCERIES_CREATE_SUCCESS";
export const GROCERIES_CREATE_FAIL = "GROCERIES_CREATE_FAIL";

export const GROCERIES_UPDATE_REQUEST = "GROCERIES_UPDATE_REQUEST";
export const GROCERIES_UPDATE_SUCCESS = "GROCERIES_UPDATE_SUCCESS";
export const GROCERIES_UPDATE_FAIL = "GROCERIES_UPDATE_FAIL";

export const GROCERIES_DELETE_REQUEST = "GROCERIES_DELETE_REQUEST";
export const GROCERIES_DELETE_SUCCESS = "GROCERIES_DELETE_SUCCESS";
export const GROCERIES_DELETE_FAIL = "GROCERIES_DELETE_FAIL";
