export const SHOPSS_LIST_REQUEST = "SHOPSS_LIST_REQUEST";
export const SHOPSS_LIST_SUCCESS = "SHOPSS_LIST_SUCCESS";
export const SHOPSS_LIST_FAIL = "SHOPSS_LIST_FAIL";

export const SHOPSS_CREATE_REQUEST = "SHOPSS_CREATE_REQUEST";
export const SHOPSS_CREATE_SUCCESS = "SHOPSS_CREATE_SUCCESS";
export const SHOPSS_CREATE_FAIL = "SHOPSS_CREATE_FAIL";

export const SHOPSS_UPDATE_REQUEST = "SHOPSS_UPDATE_REQUEST";
export const SHOPSS_UPDATE_SUCCESS = "SHOPSS_UPDATE_SUCCESS";
export const SHOPSS_UPDATE_FAIL = "SHOPSS_UPDATE_FAIL";

export const SHOPSS_DELETE_REQUEST = "SHOPSS_DELETE_REQUEST";
export const SHOPSS_DELETE_SUCCESS = "SHOPSS_DELETE_SUCCESS";
export const SHOPSS_DELETE_FAIL = "SHOPSS_DELETE_FAIL";
